Wrap code in run function
This will allow us to capture the entire output and analyze it (e. g.
retry if apt-get failed because of network errors, send e-mail in case
of error).

diff --git a/ceylon-ci b/ceylon-ci
--- a/ceylon-ci
+++ b/ceylon-ci
@@ -3,24 +3,27 @@ if [[ $(id -u) != 0 ]]; then
     echo "$0: this command must be run as root!" >&2
     exit 1
 fi
-set -o errexit # exit immediately if a command fails
-set -o errtrace # … in functions as well
-function err {
-    echo "$0: error on line $LINENO ‘$BASH_COMMAND’, exiting" >&2
+function run {
+    set -o errexit # exit immediately if a command fails
+    set -o errtrace # … in functions as well
+    function err {
+	echo "$0: error on line $LINENO ‘$BASH_COMMAND’, exiting" >&2
+    }
+    trap err ERR
+    export LC_ALL=$LANG # needed in container, apparently not set by default
+    lxc-create -n ceylon-ci -t debian
+    trap 'lxc-destroy -n ceylon-ci; err' ERR # clean up the container in any event
+    function run { lxc-start -n ceylon-ci -- "$@"; } # warning: lxc-execute doesn’t work (requires lxc within container)
+    function runin { name=$1; shift; run bash -c "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre; cd $name; $*"; } # yes, $*, not $@. Needs to be within the -c argument!
+    run apt-get install --yes --no-install-recommends openjdk-7-jdk ant git; echo $?
+    run mkdir /root/ceylon
+    runin '/root/ceylon' git clone https://github.com/ceylon/ceylon-dist.git
+    runin '/root/ceylon/ceylon-dist' ant setup
+    runin '/root/ceylon/ceylon-dist' ant publish-all
+    runin '/root/ceylon' git clone https://github.com/ceylon/ceylon-sdk.git
+    runin '/root/ceylon/ceylon-sdk' ant publish
+    runin '/root/ceylon' git clone https://github.com/ceylon/ceylon.formatter.git
+    runin '/root/ceylon/ceylon.formatter' ant test
+    lxc-destroy -n ceylon-ci
 }
-trap err ERR
-export LC_ALL=$LANG # needed in container, apparently not set by default
-lxc-create -n ceylon-ci -t debian
-trap 'lxc-destroy -n ceylon-ci; err' ERR # clean up the container in any event
-function run { lxc-start -n ceylon-ci -- "$@"; } # warning: lxc-execute doesn’t work (requires lxc within container)
-function runin { name=$1; shift; run bash -c "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre; cd $name; $*"; } # yes, $*, not $@. Needs to be within the -c argument!
-run apt-get install --yes --no-install-recommends openjdk-7-jdk ant git; echo $?
-run mkdir /root/ceylon
-runin '/root/ceylon' git clone https://github.com/ceylon/ceylon-dist.git
-runin '/root/ceylon/ceylon-dist' ant setup
-runin '/root/ceylon/ceylon-dist' ant publish-all
-runin '/root/ceylon' git clone https://github.com/ceylon/ceylon-sdk.git
-runin '/root/ceylon/ceylon-sdk' ant publish
-runin '/root/ceylon' git clone https://github.com/ceylon/ceylon.formatter.git
-runin '/root/ceylon/ceylon.formatter' ant test
-lxc-destroy -n ceylon-ci
+(run) # use subshell: don’t exit when run function exits
